# Generated by Django 4.1.3 on 2022-11-25 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Height_groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height_cm', models.FloatField()),
                ('ht_per', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Age_ref',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.TextField(max_length=5)),
                ('age_rat', models.IntegerField()),
                ('n_yet_married', models.FloatField()),
                ('married', models.FloatField()),
                ('n_married', models.FloatField()),
                ('is_obese', models.FloatField()),
                ('not_obese', models.FloatField()),
                ('height', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='spec_calculator.height_groups')),
            ],
        ),
    ]
