# Generated by Django 4.1.3 on 2022-12-03 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spec_calculator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='age_ref',
            name='height',
        ),
        migrations.AlterField(
            model_name='age_ref',
            name='age',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='age_ref',
            name='age_rat',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='Income_groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_yr', models.IntegerField()),
                ('income_ratio', models.FloatField()),
                ('age_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_groups', to='spec_calculator.age_ref')),
            ],
        ),
    ]
