# Generated by Django 4.1.3 on 2022-12-03 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spec_calculator', '0002_remove_age_ref_height_alter_age_ref_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='age_ref',
            name='age_group_pop',
            field=models.IntegerField(default=45678),
            preserve_default=False,
        ),
    ]
