# Generated by Django 4.1.3 on 2022-12-03 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spec_calculator', '0003_age_ref_age_group_pop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='age_ref',
            name='age_rat',
        ),
    ]
