# Generated by Django 4.1.3 on 2022-12-03 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spec_calculator', '0004_remove_age_ref_age_rat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='age_ref',
            old_name='is_obese',
            new_name='is_obese_rate',
        ),
        migrations.RenameField(
            model_name='age_ref',
            old_name='married',
            new_name='married_num',
        ),
        migrations.RenameField(
            model_name='age_ref',
            old_name='n_married',
            new_name='n_married_num',
        ),
        migrations.RenameField(
            model_name='age_ref',
            old_name='not_obese',
            new_name='not_obese_rate',
        ),
        migrations.AddField(
            model_name='age_ref',
            name='smoke_rate',
            field=models.FloatField(default=4),
            preserve_default=False,
        ),
    ]
